on:
  - push

jobs:
  kuberc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: MarkArts/kuberc/.github/workflows/kuberc.yml@v3
        with:
          file: ./examples/working-example.yml
