name: kuberc

on:
  workflow_call:
    inputs:
      version:
        description: 'kuberc version'
        required: false
        default: 'v3'
        type: string
      file:
        description: 'file containing the k8s resources to check'
        required: true
        type: string
      extra_args:
        description: 'extra arguments to pass to kuberc'
        required: false
        type: string
      skip_deno_install:
        description: "don't install deno but assume it's already installed"
        required: false
        default: false
        type: boolean

jobs:
  kuberc:
    runs-on: ubuntu-22.04
    steps:
      - if: not inputs.skip_deno_install
        name: cache deno installation and deno.land dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-kuberc-deno-${{ hashFiles('**/*') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno/deps/https/deno.land

      - if: not inputs.skip_deno_install
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno run http://deno.land/x/kuberc@${{ inputs.version }}/main.ts --file ${{ inputs.file }} ${{ inputs.extra_args }}